<a href="https://colab.research.google.com/github/MiguelCortezPino/etl-data-pipeline/blob/main/notebook/corredores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import pandas as pd

url = "https://raw.githubusercontent.com/MiguelCortezPino/etl-data-pipeline/refs/heads/main/data/raw/corredores.csv"

df = pd.read_csv(url)

df.head()

   id_corredor               nombre         zona    nivel  anios_experiencia
0            1    José López Flores  Paracentral      Mid                4.0
1            2    José Ortiz García     Centro     Junior                0.0
2            3   María Ramírez Cruz       Centro  SENIOR                 6.0
3            4  Fernanda Rojas Cruz          NaN  SENIOR                 8.0
4            5      Ana Gómez Rojas          NaN   Senior                4.0

In [53]:
#exploracion
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_corredor        80 non-null     int64
 1   nombre             80 non-null     object
 2   zona               63 non-null     object
 3   nivel              68 non-null     object
 4   anios_experiencia  76 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 3.3+ KB

id_corredor           0
nombre                0
zona                 17
nivel                12
anios_experiencia     4
dtype: int64

In [59]:
#Limpieza de datos
corredores = df.copy()
print(corredores['zona'].value_counts(dropna=False))

zona
NaN            17
  Centro       14
Centro         12
Occidente      11
Paracentral    10
Costa           9
Oriente         7
Name: count, dtype: int64

In [60]:
corredores['zona'] = corredores['zona'].str.strip()
print(corredores['zona'].value_counts(dropna=False))

zona
Centro         26
NaN            17
Occidente      11
Paracentral    10
Costa           9
Oriente         7
Name: count, dtype: int64